# Generated by Django 2.0.4 on 2018-04-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20180416_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_price',
            new_name='price',
        ),
    ]
