# Generated by Django 2.0.4 on 2018-04-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_download_app', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
